### PR TITLE
Simple decoder for message

### PR DESCRIPTION
**Pull request by joha2**
This decoder shows a sample implementation of how to decode this message once received. At the end of the day it should generate some source code which can be executed by some interpreter.

### CODE REVIEW

**Comment by aw1231** [comment]
There was a dependency error with travis-ci.  (All packages we use have to be on their whitelist apperently).  I've been through this before and it takes a day or two for it to get added.  https://github.com/travis-ci/apt-package-whitelist/issues/3184 is the issue.  After it gets approved we can rerun the build.  Sound good?

**Comment by joha2** [comment]
I am not sure whether I understand correctly since I am unexperienced with travis. But I only added a python source file: AFAIK there is nothing to be build there. As far as I understand the error protocol, the automatic build still does not work due to the haxelib. Is this correct?

**Comment by paulfitz** [comment]
Thanks @joha2!  @aw1231 I've sent you an invite as a collaborator, I'm just leaving on vacation, feel free to exercise your judgement on contributions if you're up for it.

**Comment by aw1231** [comment]
Yes, you are correct.  My bad.  Merged.

**Comment by aw1231** [comment]
Or rather it will be merged in about 30 mins as I cannot merge a failing build on my phone.

**Comment by joha2** [comment]
Thanks!

**Pull request merged**
