### PR TITLE
Get master to compile and work with travis

### PR DESCRIPTION
**Pull request by aw1231**
I no longer have a linux box, so I've been using travis to test my code.  Your branch works while the master branch doesn't compile.  I can of course add something substantial before we merge, but I think this might be necessary first.

### CODE REVIEW

**Comment by paulfitz** [comment]
travis testing would be useful, thanks for setting that up @aw1231.  Sorry for leaving master in a dodgy state last time I touched this. Any chance you could remove the adding real + reversion commits from this PR?

**Comment by aw1231** [comment]
I removed the real code already.  I'm still new to git, so I'm not sure what you mean by the reversion commit?

**Comment by aw1231** [comment]
I really screwed up trying to figure out what to revert.  Sorry about that.

**Comment by paulfitz** [comment]
No worries. Reverting isn't really what you want when preparing a PR. If you look at the commits in this PR, at most 3 are useful (adding travis, plus maybe the two work-in-progress commits I had lurking that you found) and the rest are noise.  If you reset this branch to commit `86a29b7` it would make a better PR.  Feel free to close this and retry, I won't hold it against you.  I could also cherry-pick the useful commits from this PR if you'd rather not fiddle further.

**Comment by aw1231** [comment]
How do I reset?  I thought (naively) that the way to revert back to was to use the revert command.  Is there a better way?  Once I figure all this out I'll send a new pull request.

**Pull request closed without merging**
